# Generated by Django 3.2.2 on 2021-11-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='about',
            field=models.TextField(),
        ),
    ]
