# Generated by Django 3.2.2 on 2021-11-12 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_alter_talent_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='slug',
            field=models.SlugField(blank=True, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), unique=True),
        ),
    ]
