# Generated by Django 3.2.2 on 2021-11-12 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_alter_talent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
