# Generated by Django 3.2.2 on 2021-11-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_alter_talent_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='views',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Talent',
        ),
    ]
