# Generated by Django 3.2.9 on 2022-01-07 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0008_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='registered_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='startup',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='what_we_offer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
