# Generated by Django 3.2.2 on 2021-10-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='status',
            field=models.CharField(choices=[('shortlisted', 'shortlisted'), ('rejected', 'rejected'), ('reviewing', 'reviewing'), ('interviewed', 'interviewed'), ('offergiven', 'offergiven')], default='reviewing', max_length=100),
        ),
    ]
