# Generated by Django 3.2.2 on 2021-10-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_opportunity_id_matches_opportunity_matched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='opportunity_matched',
            new_name='opportunity_id',
        ),
    ]
