# Generated by Django 3.2.2 on 2021-10-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_opportunity_matched_matches_opportunity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='startup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
