# Generated by Django 3.2.2 on 2021-10-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_matches_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='opportunity_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
