# Generated by Django 3.2.2 on 2021-10-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0018_opportunity_matched'),
        ('dashboard', '0006_matches_opportunity_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='opportunity',
            field=models.ManyToManyField(to='opportunity.Opportunity'),
        ),
    ]
