# Generated by Django 3.2.9 on 2021-12-14 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
