# Generated by Django 3.2.9 on 2022-01-21 13:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userauth', '0003_profile_location'),
        ('dashboard', '0014_alter_message_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateTimeField(default=datetime.datetime.now)),
                ('rating_value', models.FloatField(max_length=100)),
                ('interviewer', models.CharField(max_length=100, null=True)),
                ('interviewer_title', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('rating_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rating_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.profile')),
            ],
        ),
    ]
