# Generated by Django 3.2.9 on 2022-01-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_rating_rating_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='interviewer',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='interviewer_title',
        ),
    ]
