# Generated by Django 3.2.9 on 2022-01-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0015_skill_experience'),
        ('dashboard', '0017_auto_20220121_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talents.talent'),
        ),
    ]
