# Generated by Django 3.2.9 on 2022-01-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0013_startup_rating'),
        ('dashboard', '0020_remove_matches_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startups.startup'),
        ),
    ]
