# Generated by Django 3.2.9 on 2022-01-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_matches_startup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='opportunity_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
