# Generated by Django 3.2.9 on 2022-01-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_matches_opportunity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='opportunity_id',
        ),
    ]
