# Generated by Django 3.2.2 on 2022-02-07 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0027_package_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_payment',
            name='the_startup',
        ),
        migrations.AddField(
            model_name='package_payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
