# Generated by Django 3.2.2 on 2022-02-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20220207_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_payment',
            name='amount_paid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
