# Generated by Django 3.2.2 on 2022-02-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_package_payment_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Opportunity_listing', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100)),
                ('talent_due_deligency', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100)),
                ('legal', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100)),
                ('payroll', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100)),
            ],
        ),
    ]
