# Generated by Django 3.2.2 on 2022-02-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Opportunity_listing',
            new_name='opportunity_listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='charge',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
