# Generated by Django 3.2.2 on 2022-02-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20220226_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_payment',
            name='txt_ref',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
