# Generated by Django 3.2.2 on 2022-02-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20220227_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_payment',
            name='package_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.listing'),
        ),
    ]
