# Generated by Django 3.2.2 on 2022-02-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_package_payment_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_payment',
            name='posted_opportunity',
            field=models.IntegerField(),
        ),
    ]
