# Generated by Django 3.2.2 on 2022-03-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_package_payment_posted_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_payment',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
