# Generated by Django 3.2.2 on 2022-05-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('junior_roles', 'junior_roles'), ('mid_level_roles', 'mid_level_roles'), ('senior_roles', 'senior_roles')], max_length=100, null=True),
        ),
    ]
