# Generated by Django 3.2.2 on 2021-06-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_auto_20210625_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
