# Generated by Django 3.2.2 on 2021-06-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_alter_opportunity_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='sectors',
            new_name='sector',
        ),
    ]
