# Generated by Django 3.2.2 on 2021-06-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0005_alter_opportunity_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='salary_range',
            field=models.IntegerField(default=0),
        ),
    ]
