# Generated by Django 3.2.2 on 2021-06-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0007_alter_opportunity_salary_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='salary_range',
            field=models.CharField(choices=[('0 - 500,000/-', '0 - 500,000/-'), ('500,000 - 1,000,000/-', '500,000 - 1,000,000/-'), ('1,000,000 - 3,000,000/-', '1,000,000 - 3,000,000/-'), ('3,000,000 - 5,000,000/-', '3,000,000 - 5,000,000/-'), ('5,000,000 - 8,000,000/-', '5,000,000 - 8,000,000/-'), ('8 and More', '8 and More')], max_length=100),
        ),
    ]
