# Generated by Django 3.2.2 on 2021-06-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0008_alter_opportunity_salary_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='salary_range',
            field=models.CharField(choices=[('0 - 500k', '0 - 500k'), ('500k - 1M', '500k - 1M'), ('1M - 3M', '1M - 3M'), ('3M - 5M', '3M - 5M'), ('5M - 8M', '5M - 8M'), ('8M and More', '8M and More')], max_length=100),
        ),
    ]
