# Generated by Django 3.2.2 on 2021-10-06 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0009_alter_opportunity_salary_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
