# Generated by Django 3.2.2 on 2021-10-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0010_opportunity_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('expired', 'expired')], default='active', max_length=100),
        ),
    ]
