# Generated by Django 3.2.2 on 2021-10-08 09:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0012_remove_opportunity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='duties_and_responsibilities',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='skills_required',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
