# Generated by Django 3.2.2 on 2021-10-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0013_auto_20211008_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='experience',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
