# Generated by Django 3.2.2 on 2021-10-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0014_opportunity_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='matches',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
