# Generated by Django 3.2.2 on 2021-10-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_matches_opportunity_title'),
        ('opportunity', '0015_opportunity_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='matches',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='matches',
            field=models.ManyToManyField(to='dashboard.Matches'),
        ),
    ]
