# Generated by Django 3.2.2 on 2021-10-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0016_auto_20211015_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='matches',
        ),
    ]
