# Generated by Django 3.2.2 on 2021-11-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0018_opportunity_matched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='deadline',
            field=models.DateField(auto_now=True),
        ),
    ]
