# Generated by Django 3.2.2 on 2021-11-10 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0019_alter_opportunity_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
