# Generated by Django 3.2.2 on 2021-11-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0020_alter_opportunity_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('full time', 'full time'), ('remote', 'remote'), ('contractual', 'contractual'), ('internship', 'internship'), ('voluntering', 'voluntering'), ('freelance', 'freelance'), ('part-time', 'part-time'), ('temporary', 'temporary'), ('internship', 'internship')], max_length=100),
        ),
    ]
