# Generated by Django 3.2.9 on 2022-01-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0023_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
    ]
