# Generated by Django 3.2.9 on 2022-01-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0026_opportunity_expred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='expred',
            new_name='expired',
        ),
    ]
