# Generated by Django 3.2.9 on 2022-01-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0027_rename_expred_opportunity_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='expired',
        ),
    ]
