# Generated by Django 3.2.9 on 2022-01-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0028_remove_opportunity_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
