# Generated by Django 3.2.9 on 2022-01-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0029_alter_opportunity_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='company_name',
        ),
    ]
