# Generated by Django 3.2.2 on 2021-06-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talent',
        ),
    ]
