# Generated by Django 3.2.2 on 2021-11-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='experince',
            field=models.CharField(choices=[('Less than 1 Year', 'Less than 1 Year'), ('2-5 years', '2-5 years'), ('5-7 years', '5-7 years'), ('7-10 years', '7-10 years'), ('10 years and above', '10 years and above')], max_length=100),
        ),
    ]
