# Generated by Django 3.2.2 on 2021-11-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0003_rename_salary_expectaion_talent_salary_expectatioon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talent',
            old_name='salary_expectatioon',
            new_name='salary_expectation',
        ),
    ]
