# Generated by Django 3.2.2 on 2021-11-12 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0005_rename_experince_talent_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='still_working',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
