# Generated by Django 3.2.2 on 2021-11-12 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0007_alter_experience_finish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='subject',
            new_name='speciality',
        ),
    ]
