# Generated by Django 3.2.2 on 2021-11-15 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0008_rename_subject_education_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='finish_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
