# Generated by Django 3.2.2 on 2021-11-15 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0010_auto_20211115_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='finish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
