# Generated by Django 3.2.2 on 2021-11-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0011_auto_20211115_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='still_working',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
