# Generated by Django 3.2.2 on 2021-11-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0012_alter_experience_still_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='still_working',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=100, null=True),
        ),
    ]
