# Generated by Django 3.2.2 on 2021-11-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0013_alter_experience_still_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
